#!/usr/bin/env php
<?php

error_reporting(E_ALL);

require_once('lib/PHPGGC.php');

$x = new PHPGGC();

try
{
    $x->generate();
}
catch(\PHPGGC\Exception $e)
{
    print("ERROR: " . $e->getMessage() . "\n");
}
